# Root directory of your project
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Command to build your app
  cmd = "go build -o ./tmp/main ./cmd"
  bin = "./tmp/main"

  # Reduce rebuild delay (ms) for faster feedback
  delay = 500

  # Ignore unnecessary dirs (public assets, docs, client, etc.)
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "docs", "client"]

  # Skip Go test files
  exclude_regex = ["_test.go"]

  # Watch only these file types
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json", "env"]

  # Log build errors
  log = "build-errors.log"

  # Don’t stop server if build fails
  stop_on_error = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Show timestamps for debugging
  time = true
  silent = false
  main_only = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true   # Clears screen on rebuild
  keep_scroll = true
